//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Security_ServiceEntities : DbContext
    {
        public Security_ServiceEntities()
            : base("name=Security_ServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentCriterias> AssessmentCriterias { get; set; }
        public virtual DbSet<Checklists> Checklists { get; set; }
        public virtual DbSet<Citys> Citys { get; set; }
        public virtual DbSet<Continents> Continents { get; set; }
        public virtual DbSet<Countrys> Countrys { get; set; }
        public virtual DbSet<Crops> Crops { get; set; }
        public virtual DbSet<Evidences> Evidences { get; set; }
        public virtual DbSet<FarmCrops> FarmCrops { get; set; }
        public virtual DbSet<Farms> Farms { get; set; }
        public virtual DbSet<Fertilizations> Fertilizations { get; set; }
        public virtual DbSet<FertilizationSupplies> FertilizationSupplies { get; set; }
        public virtual DbSet<Fumigations> Fumigations { get; set; }
        public virtual DbSet<FumigationSupplies> FumigationSupplies { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Qualifications> Qualifications { get; set; }
        public virtual DbSet<ReviewEvidences> ReviewEvidences { get; set; }
        public virtual DbSet<ReviewTechnicals> ReviewTechnicals { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RoleViews> RoleViews { get; set; }
        public virtual DbSet<Supplies> Supplies { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Views> Views { get; set; }
    }
}
