//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewTechnicals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewTechnicals()
        {
            this.Fertilizations = new HashSet<Fertilizations>();
            this.Fumigations = new HashSet<Fumigations>();
            this.ReviewEvidences = new HashSet<ReviewEvidences>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date_review { get; set; }
        public string Code { get; set; }
        public string Observation { get; set; }
        public int FarmId { get; set; }
        public int TecnicoId { get; set; }
        public int ChecklistId { get; set; }
        public bool State { get; set; }
        public System.DateTime Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<System.DateTime> Deleted_at { get; set; }
    
        public virtual Checklists Checklists { get; set; }
        public virtual Farms Farms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fertilizations> Fertilizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fumigations> Fumigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewEvidences> ReviewEvidences { get; set; }
        public virtual Users Users { get; set; }
    }
}
